In [2]:
import pandas as pd
import tushare as ts

In [3]:
pro = ts.pro_api('55bc1b5c9eb018b0e5f848266ab84d6902db1e0b4d389c44cb42940a')

In [5]:
data = pro.daily(ts_code='000061.SZ', start_date='20180101', end_date='20190101')
data.to_csv('daily_share.csv')
data.head(10)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000061.SZ,20181228,4.83,4.88,4.81,4.85,4.81,0.04,0.8316,36631.84,17756.246
1,000061.SZ,20181227,4.99,5.02,4.80,4.81,4.91,-0.10,-2.0367,59757.01,29316.285
2,000061.SZ,20181226,5.02,5.02,4.87,4.91,5.03,-0.12,-2.3857,73012.65,35955.318
3,000061.SZ,20181225,5.13,5.15,4.81,5.03,5.19,-0.16,-3.0829,93694.17,46780.731
4,000061.SZ,20181224,4.98,5.22,4.96,5.19,4.96,0.23,4.6371,118030.68,60755.546
5,000061.SZ,20181221,5.14,5.16,4.93,4.96,5.14,-0.18,-3.5019,97390.22,48878.281
6,000061.SZ,20181220,5.17,5.22,5.10,5.14,5.15,-0.01,-0.1942,79767.97,41141.726
7,000061.SZ,20181219,5.35,5.35,5.15,5.15,5.33,-0.18,-3.3771,118225.75,61738.698
8,000061.SZ,20181218,5.48,5.48,5.23,5.33,5.56,-0.23,-4.1367,187031.06,99994.758
9,000061.SZ,20181217,5.20,5.64,5.19,5.56,5.13,0.43,8.3821,304727.05,166908.688

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ts_code     233 non-null    object
 1   trade_date  233 non-null    object
 2   open        233 non-null    float64
 3   high        233 non-null    float64
 4   low         233 non-null    float64
 5   close       233 non-null    float64
 6   pre_close   233 non-null    float64
 7   change      233 non-null    float64
 8   pct_chg     233 non-null    float64
 9   vol         233 non-null    float64
 10  amount      233 non-null    float64
dtypes: float64(9), object(2)
memory usage: 20.1+ KB

In [18]:
data = pro.stock_basic(exchange='', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
data

        ts_code  symbol     name  area industry list_date
0     000001.SZ  000001     平安银行    深圳       银行  19910403
1     000002.SZ  000002      万科A    深圳     全国地产  19910129
2     000004.SZ  000004     ST国华    深圳     软件服务  19910114
3     000005.SZ  000005     ST星源    深圳     环境保护  19901210
4     000006.SZ  000006     深振业A    深圳     区域地产  19920427
...         ...     ...      ...   ...      ...       ...
5071  873223.BJ  873223     荣亿精密  None     None  20220609
5072  873305.BJ  873305     九菱科技  None     None  20221221
5073  873339.BJ  873339     恒太照明  None     None  20221117
5074  873527.BJ  873527      夜光明  None     None  20221027
5075  689009.SH  689009  九号公司-WD    北京      摩托车  20201029

[5076 rows x 6 columns]

In [19]:
st_daily_share = pro.daily(ts_code='000004.SZ,', start_date='20180101', end_date='20190101')
st_daily_share.to_csv('000004_st_daily_share.csv')
st_daily_share.head(10)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000004.SZ,20181228,15.73,16.26,15.73,16.03,16.03,0.00,0.0000,1671.00,2685.455
1,000004.SZ,20181227,16.61,16.61,16.03,16.03,16.31,-0.28,-1.7167,1975.00,3226.195
2,000004.SZ,20181226,16.18,16.45,16.16,16.31,16.17,0.14,0.8658,1634.00,2653.802
3,000004.SZ,20181225,16.42,16.42,15.92,16.17,16.45,-0.28,-1.7021,2295.00,3698.461
4,000004.SZ,20181224,16.29,16.50,16.08,16.45,16.27,0.18,1.1063,2307.00,3776.770
5,000004.SZ,20181221,16.42,16.53,16.17,16.27,16.44,-0.17,-1.0341,2317.00,3770.916
6,000004.SZ,20181220,16.49,16.64,16.30,16.44,16.43,0.01,0.0609,2478.00,4080.480
7,000004.SZ,20181219,16.92,16.92,16.32,16.43,16.91,-0.48,-2.8386,5964.00,9869.709
8,000004.SZ,20181218,17.40,17.40,16.83,16.91,17.56,-0.65,-3.7016,6843.06,11673.500
9,000004.SZ,20181217,17.60,18.11,17.25,17.56,18.26,-0.70,-3.8335,16320.41,28666.528

In [13]:
agriculture_products_daily_share = pro.daily(ts_code='000061.SZ', start_date='20180101', end_date='20190101')
agriculture_products_daily_share.to_csv('agriculture_products_daily_share.csv')
agriculture_products_daily_share.head(10)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000061.SZ,20181228,4.83,4.88,4.81,4.85,4.81,0.04,0.8316,36631.84,17756.246
1,000061.SZ,20181227,4.99,5.02,4.80,4.81,4.91,-0.10,-2.0367,59757.01,29316.285
2,000061.SZ,20181226,5.02,5.02,4.87,4.91,5.03,-0.12,-2.3857,73012.65,35955.318
3,000061.SZ,20181225,5.13,5.15,4.81,5.03,5.19,-0.16,-3.0829,93694.17,46780.731
4,000061.SZ,20181224,4.98,5.22,4.96,5.19,4.96,0.23,4.6371,118030.68,60755.546
5,000061.SZ,20181221,5.14,5.16,4.93,4.96,5.14,-0.18,-3.5019,97390.22,48878.281
6,000061.SZ,20181220,5.17,5.22,5.10,5.14,5.15,-0.01,-0.1942,79767.97,41141.726
7,000061.SZ,20181219,5.35,5.35,5.15,5.15,5.33,-0.18,-3.3771,118225.75,61738.698
8,000061.SZ,20181218,5.48,5.48,5.23,5.33,5.56,-0.23,-4.1367,187031.06,99994.758
9,000061.SZ,20181217,5.20,5.64,5.19,5.56,5.13,0.43,8.3821,304727.05,166908.688

In [23]:
st_df = pd.read_csv('000004_st_daily_share.csv', parse_dates=['trade_date'])[['trade_date', 'close']]
agriculture_products_df = pd.read_csv('000061_农产品_daily_share.csv', parse_dates=['trade_date'])[
    ['trade_date', 'close']]
st_df = st_df.rename(columns={'close': 'software_close'})
agriculture_products_df = agriculture_products_df.rename(columns={'close': 'agriculture_products_close'})
data_merge = pd.merge(st_df, agriculture_products_df, how='inner', on='trade_date')
data_merge.to_excel('software_and_agriculture_products_share_price.xlsx')
data_merge

    trade_date  software_close  agriculture_products_close
0   2018-12-28           16.03                        4.85
1   2018-12-27           16.03                        4.81
2   2018-12-26           16.31                        4.91
3   2018-12-25           16.17                        5.03
4   2018-12-24           16.45                        5.19
..         ...             ...                         ...
213 2018-01-08           22.84                        7.84
214 2018-01-05           23.18                        8.04
215 2018-01-04           23.24                        7.70
216 2018-01-03           23.80                        7.71
217 2018-01-02           22.34                        7.70

[218 rows x 3 columns]

## 皮尔特系数——线性相关

In [25]:
from scipy.stats import pearsonr

In [27]:
corr = pearsonr(data_merge['software_close'], data_merge['agriculture_products_close'])
print('相关系数r值为' + str(corr[0]) + ', 显著水平P值为' + str(corr[1]))

相关系数r值为0.8895298330254658, 显著水平P值为2.0007485543818567e-75