In [29]:
import pandas as pd
import requests
from bs4 import BeautifulSoup


class BSDD:
    """ 爬取最近30天数据"""

    def __init__(self, url: str, headers: dict = None, params: dict = None):
        self.url = url
        self.headers = headers
        self.params = params
        self.resp = None
        self.soup: BeautifulSoup = None
        self.data: dict = {
            "图书排名": [],
            "图书名称": [],
            "图书作者": [],
            "图书出版时间": [],
            "图书出版社": [],
            "图书价格": [],
        }
        self.current_page = 1
        self.current_page_count = 1
        self.total_count = 0

    def parse_html(self):
        li_list = self.soup.select(".bang_list li")
        self.current_page_count = 1
        for li in li_list:
            print(f"正在解析第{self.current_page}页的第{self.current_page_count}条数据")
            self.data["图书排名"].append(li.select(".list_num")[0].text.replace(".", ""))
            self.data["图书名称"].append(li.select(".name a")[0].text)
            self.data["图书作者"].append(li.select(".publisher_info")[0].text)
            self.data["图书出版时间"].append(li.select(".publisher_info span")[0].text)
            self.data["图书出版社"].append(li.select(".publisher_info")[1].select("a")[0].text)
            self.data["图书价格"].append(float(li.select(".price .price_n")[0].text.replace("￥", "")[1:]))
            self.current_page_count += 1
            self.total_count += 1

    def crawler(self, star: int = 1, end: int = 20):
        self.current_page = star
        while self.current_page <= end:
            self.url = self.url.rsplit('-', maxsplit=1)[0] + "-" + str(self.current_page)
            self.resp = requests.get(url=self.url, headers=self.headers, params=self.params)
            print(f"=====正在爬取第{self.current_page}页数据,目前数据量为：{self.total_count}=====")
            self.soup = BeautifulSoup(self.resp.text, "lxml")
            self.parse_html()
            self.current_page += 1
        print("=" * 20, f"爬取数据量为：{self.total_count}", "=" * 20, )

In [30]:
headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"}
url = "http://bang.dangdang.com/books/bestsellers/01.00.00.00.00.00-recent30-0-0-1-2"
bsdd = BSDD(url, headers=headers)
bsdd.crawler(end=10)

=====正在爬取第1页数据,目前数据量为：0=====
正在解析第1页的第1条数据
正在解析第1页的第2条数据
正在解析第1页的第3条数据
正在解析第1页的第4条数据
正在解析第1页的第5条数据
正在解析第1页的第6条数据
正在解析第1页的第7条数据
正在解析第1页的第8条数据
正在解析第1页的第9条数据
正在解析第1页的第10条数据
正在解析第1页的第11条数据
正在解析第1页的第12条数据
正在解析第1页的第13条数据
正在解析第1页的第14条数据
正在解析第1页的第15条数据
正在解析第1页的第16条数据
正在解析第1页的第17条数据
正在解析第1页的第18条数据
正在解析第1页的第19条数据
正在解析第1页的第20条数据
=====正在爬取第2页数据,目前数据量为：20=====
正在解析第2页的第1条数据
正在解析第2页的第2条数据
正在解析第2页的第3条数据
正在解析第2页的第4条数据
正在解析第2页的第5条数据
正在解析第2页的第6条数据
正在解析第2页的第7条数据
正在解析第2页的第8条数据
正在解析第2页的第9条数据
正在解析第2页的第10条数据
正在解析第2页的第11条数据
正在解析第2页的第12条数据
正在解析第2页的第13条数据
正在解析第2页的第14条数据
正在解析第2页的第15条数据
正在解析第2页的第16条数据
正在解析第2页的第17条数据
正在解析第2页的第18条数据
正在解析第2页的第19条数据
正在解析第2页的第20条数据
=====正在爬取第3页数据,目前数据量为：40=====
正在解析第3页的第1条数据
正在解析第3页的第2条数据
正在解析第3页的第3条数据
正在解析第3页的第4条数据
正在解析第3页的第5条数据
正在解析第3页的第6条数据
正在解析第3页的第7条数据
正在解析第3页的第8条数据
正在解析第3页的第9条数据
正在解析第3页的第10条数据
正在解析第3页的第11条数据
正在解析第3页的第12条数据
正在解析第3页的第13条数据
正在解析第3页的第14条数据
正在解析第3页的第15条数据
正在解析第3页的第16条数据
正在解析第3页的第17条数据
正在解析第3页的第18条数据
正在解析第3页的第19条数据
正在解析第3页的第20条数据
=====正在爬取第4页数据,目前数据量为：60=====
正在解析第4页的第1条数据
正在解析第4页的第2条数据
正在解析第4页的第3条数据
正在解析第4页的第4条数据
正在解析第4页的第5条数据
正在解析第4页的第6条数据
正在解析第4页的第7条数据
正在解析第4页的第8条数据
正在解析第4页的第9条数据
正在解析第4页的第10条数据
正在解析第4页的第11条数据
正在解析第4页的第12条数据
正在解析第4页的第13条数据
正在解析第4页的第14条数据
正在解析第4页的第15条数据
正在解析第4页的第16条数据
正在解析第4页的第17条数据
正在解析第4页的第18条数据
正在解析第4页的第19条数据
正在解析第4页的第20条数据
=====正在爬取第5页数据,目前数据量为：80=====
正在解析第5页的第1条数据
正在解析第5页的第2条数据
正在解析第5页的第3条数据
正在解析第5页的第4条数据
正在解析第5页的第5条数据
正在解析第5页的第6条数据
正在解析第5页的第7条数据
正在解析第5页的第8条数据
正在解析第5页的第9条数据
正在解析第5页的第10条数据
正在解析第5页的第11条数据
正在解析第5页的第12条数据
正在解析第5页的第13条数据
正在解析第5页的第14条数据
正在解析第5页的第15条数据
正在解析第5页的第16条数据
正在解析第5页的第17条数据
正在解析第5页的第18条数据
正在解析第5页的第19条数据
正在解析第5页的第20条数据
=====正在爬取第6页数据,目前数据量为：100=====
正在解析第6页的第1条数据
正在解析第6页的第2条数据
正在解析第6页的第3条数据
正在解析第6页的第4条数据
正在解析第6页的第5条数据
正在解析第6页的第6条数据
正在解析第6页的第7条数据
正在解析第6页的第8条数据
正在解析第6页的第9条数据
正在解析第6页的第10条数据
正在解析第6页的第11条数据
正在解析第6页的第12条数据
正在解析第6页的第13条数据
正在解析第6页的第14条数据
正在解析第6页的第15条数据
正在解析第6页的第16条数据
正在解析第6页的第17条数据
正在解析第6页的第18条数据
正在解析第6页的第19条数据
正在解析第6页的第20条数据
=====正在爬取第7页数据,目前数据量为：120=====
正在解析第7页的第1条数据
正在解析第7页的第2条数据
正在解析第7页的第3条数据
正在解析第7页的第4条数据
正在解析第7页的第5条数据
正在解析第7页的第6条数据
正在解析第7页的第7条数据
正在解析第7页的第8条数据
正在解析第7页的第9条数据
正在解析第7页的第10条数据
正在解析第7页的第11条数据
正在解析第7页的第12条数据
正在解析第7页的第13条数据
正在解析第7页的第14条数据
正在解析第7页的第15条数据
正在解析第7页的第16条数据
正在解析第7页的第17条数据
正在解析第7页的第18条数据
正在解析第7页的第19条数据
正在解析第7页的第20条数据
=====正在爬取第8页数据,目前数据量为：140=====
正在解析第8页的第1条数据
正在解析第8页的第2条数据
正在解析第8页的第3条数据
正在解析第8页的第4条数据
正在解析第8页的第5条数据
正在解析第8页的第6条数据
正在解析第8页的第7条数据
正在解析第8页的第8条数据
正在解析第8页的第9条数据
正在解析第8页的第10条数据
正在解析第8页的第11条数据
正在解析第8页的第12条数据
正在解析第8页的第13条数据
正在解析第8页的第14条数据
正在解析第8页的第15条数据
正在解析第8页的第16条数据
正在解析第8页的第17条数据
正在解析第8页的第18条数据
正在解析第8页的第19条数据
正在解析第8页的第20条数据
=====正在爬取第9页数据,目前数据量为：160=====
正在解析第9页的第1条数据
正在解析第9页的第2条数据
正在解析第9页的第3条数据
正在解析第9页的第4条数据
正在解析第9页的第5条数据
正在解析第9页的第6条数据
正在解析第9页的第7条数据
正在解析第9页的第8条数据
正在解析第9页的第9条数据
正在解析第9页的第10条数据
正在解析第9页的第11条数据
正在解析第9页的第12条数据
正在解析第9页的第13条数据
正在解析第9页的第14条数据
正在解析第9页的第15条数据
正在解析第9页的第16条数据
正在解析第9页的第17条数据
正在解析第9页的第18条数据
正在解析第9页的第19条数据
正在解析第9页的第20条数据
=====正在爬取第10页数据,目前数据量为：180=====
正在解析第10页的第1条数据
正在解析第10页的第2条数据
正在解析第10页的第3条数据
正在解析第10页的第4条数据
正在解析第10页的第5条数据
正在解析第10页的第6条数据
正在解析第10页的第7条数据
正在解析第10页的第8条数据
正在解析第10页的第9条数据
正在解析第10页的第10条数据
正在解析第10页的第11条数据
正在解析第10页的第12条数据
正在解析第10页的第13条数据
正在解析第10页的第14条数据
正在解析第10页的第15条数据
正在解析第10页的第16条数据
正在解析第10页的第17条数据
正在解析第10页的第18条数据
正在解析第10页的第19条数据
正在解析第10页的第20条数据
==================== 爬取数据量为：200 ====================

In [31]:
ds = pd.DataFrame(bsdd.data)
ds

,图书排名,图书名称,图书作者,图书出版时间,图书出版社,图书价格
0,1,经典常谈朱自清（《语文》推荐阅读丛书） 人民文学出版社,朱自清,2022-08-01,人民文学出版社,10.0
1,2,真希望你也喜欢自己（房琪shou部作品重磅上市！写给所有年轻人的...,房琪kiki,2022-09-28,北京联合出版有限公司,37.3
2,3,你也走了很远的路吧（新增2万余字，4篇文章，关于特殊时期成长的...,"卢思浩 著,博集天卷 出品",2022-09-26,湖南文艺出版社,24.9
3,4,三体：全三册 刘慈欣代表作，亚洲“雨果奖”获奖作品！,刘慈欣,2010-11-01,重庆出版社,44.7
4,5,长安的荔枝,"马伯庸 著,博集天卷 出品",2022-10-31,湖南文艺出版社,29.0
...,...,...,...,...,...,...
195,196,明朝那些事儿增补版.全集,当年明月 著,2017-05-01,北京联合出版有限公司,202.5
196,197,白鹅赶路（陈伯吹儿童文学奖等多项童书大奖得主彭万州赠予孩子的...,彭万洲 著；小当当出品,2019-01-01,中译出版社（原中国对外翻译出版公司）,12.2
197,198,邂逅中国 走遍中国 图说天下 国家地理 套装共5册[精选套装],赵晓玉 ，郝娟菡，《图说天下.国家地理系列》编委会,2017-11-01,北京联合出版公司,39.8
198,199,三国演义 四大名著五年级下册推荐阅读(中小学生课外阅读指导丛书...,（明）罗贯中,2021-06-01,时代文艺出版社,6.5
199,200,兄弟（余华巅峰之作！有的人活着，生死疲劳；有的人活着，任性逍...,余华 著 ，新经典 出品,2022-07-01,北京十月文艺出版社,54.5

In [32]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   图书排名    200 non-null    object
 1   图书名称    200 non-null    object
 2   图书作者    200 non-null    object
 3   图书出版时间  200 non-null    object
 4   图书出版社   200 non-null    object
 5   图书价格    200 non-null    float64
dtypes: float64(1), object(5)
memory usage: 9.5+ KB

In [33]:
ds.describe()

             图书价格
count  200.000000
mean    28.520350
std     27.815779
min      5.000000
25%     13.000000
50%     21.500000
75%     31.200000
max    202.500000

In [34]:
ds.isnull()

      图书排名   图书名称   图书作者  图书出版时间  图书出版社   图书价格
0    False  False  False   False  False  False
1    False  False  False   False  False  False
2    False  False  False   False  False  False
3    False  False  False   False  False  False
4    False  False  False   False  False  False
..     ...    ...    ...     ...    ...    ...
195  False  False  False   False  False  False
196  False  False  False   False  False  False
197  False  False  False   False  False  False
198  False  False  False   False  False  False
199  False  False  False   False  False  False

[200 rows x 6 columns]

In [35]:
ds.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [36]:
ds["图书价格"][ds["图书价格"] > 100]

21     108.4
84     168.0
102    144.0
175    177.5
192    137.5
195    202.5
Name: 图书价格, dtype: float64

In [39]:
ds["图书价格"][ds["图书价格"] > 100] = None
ds = ds.dropna()

/Users/reddyfan/code/proj/RDVS/rdvs/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/reddyfan/code/proj/RDVS/rdvs/venv/lib/python3.7/site-packages/pandas/core/generic.py:8870: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [41]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   图书排名    194 non-null    object
 1   图书名称    194 non-null    object
 2   图书作者    194 non-null    object
 3   图书出版时间  194 non-null    object
 4   图书出版社   194 non-null    object
 5   图书价格    194 non-null    float64
dtypes: float64(1), object(5)
memory usage: 10.6+ KB

In [42]:
ds.to_excel("当当网图书销售排行.xlsx",encoding="utf-8",index=False)