In [6]:
import pandas as pd
import tushare as ts

In [4]:

pro = ts.pro_api('55bc1b5c9eb018b0e5f848266ab84d6902db1e0b4d389c44cb42940a')
#
# data = pro.stock_basic(exchange='SSE', list_status='L', fields='ts_code,symbol,name,area,industry,list_date')
# data

NameError: name 'ts' is not defined

In [3]:
df = pro.daily(ts_code='600807.SH', start_date='20220101')

df.to_csv('shareSH.csv')
df

NameError: name 'pro' is not defined

In [7]:
TianYe = pd.read_csv('shareSH.csv', index_col='trade_date', parse_dates=['trade_date'])
TianYe

,Unnamed: 0,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,,
2023-01-20,0,600807.SH,3.44,3.50,3.42,3.50,3.42,0.08,2.3392,52855.01,18357.009
2023-01-19,1,600807.SH,3.42,3.44,3.40,3.42,3.42,0.00,0.0000,41190.00,14109.431
2023-01-18,2,600807.SH,3.40,3.43,3.39,3.42,3.40,0.02,0.5882,37379.00,12765.340
2023-01-17,3,600807.SH,3.42,3.44,3.38,3.40,3.43,-0.03,-0.8746,45833.00,15580.964
2023-01-16,4,600807.SH,3.48,3.48,3.40,3.43,3.45,-0.02,-0.5797,67378.18,23070.396
...,...,...,...,...,...,...,...,...,...,...,...
2022-01-10,251,600807.SH,3.95,4.27,3.94,4.13,3.94,0.19,4.8223,324008.17,133195.899
2022-01-07,252,600807.SH,4.01,4.10,3.92,3.94,3.96,-0.02,-0.5051,256473.00,102896.981
2022-01-06,253,600807.SH,3.95,4.04,3.91,3.96,3.93,0.03,0.7634,180569.91,71672.646
2022-01-05,254,600807.SH,4.04,4.08,3.90,3.93,4.05,-0.12,-2.9630,276351.01,109760.930
2022-01-04,255,600807.SH,4.14,4.18,4.01,4.05,4.10,-0.05,-1.2195,325834.21,132864.014

In [24]:
month_first = TianYe.resample('M').first()
month_first_money = month_first['open'].sum() * 1000
display(month_first, month_first_money)

,Unnamed: 0,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,,
2022-01-31,255,600807.SH,4.14,4.18,4.01,4.05,4.10,-0.05,-1.2195,325834.21,132864.014
2022-02-28,236,600807.SH,4.40,4.45,4.22,4.34,4.17,0.17,4.0767,306709.00,132958.765
2022-03-31,220,600807.SH,4.53,4.62,4.42,4.60,4.57,0.03,0.6565,396134.60,180116.195
2022-04-30,197,600807.SH,4.72,4.91,4.69,4.84,4.80,0.04,0.8333,455494.00,219160.344
2022-05-31,178,600807.SH,3.53,3.57,3.44,3.50,3.52,-0.02,-0.5682,172134.37,60229.589
2022-06-30,159,600807.SH,3.71,3.96,3.67,3.82,3.71,0.11,2.9650,262351.57,99737.917
2022-07-31,138,600807.SH,3.83,3.85,3.78,3.81,3.83,-0.02,-0.5222,94932.03,36199.577
2022-08-31,117,600807.SH,3.94,3.96,3.86,3.89,3.93,-0.04,-1.0178,83737.11,32627.264
2022-09-30,94,600807.SH,3.51,3.56,3.50,3.51,3.51,0.00,0.0000,46293.65,16327.891
2022-10-31,73,600807.SH,3.30,3.37,3.24,3.27,3.27,0.00,0.0000,55689.30,18414.935
2022-11-30,57,600807.SH,3.28,3.32,3.28,3.31,3.28,0.03,0.9146,48554.00,16022.511
2022-12-31,35,600807.SH,3.76,3.80,3.69,3.70,3.75,-0.05,-1.3333,120373.03,44866.597
2023-01-31,13,600807.SH,3.39,3.50,3.39,3.49,3.40,0.09,2.6471,69073.00,23795.373

50039.99999999999

In [25]:
month_max = TianYe.resample('M').last()
month_max_money = month_max['close'].sum() * 1000
get_money = month_max_money - month_first_money
get_money

-799.9999999999854

In [2]:
month_max_money

NameError: name 'month_max_money' is not defined

In [1]:
month_max

NameError: name 'month_max' is not defined