# 选取指标

## 统计热门城市

### 加载数据

In [16]:
import pandas as pd

from store.db.db_store import Mongo

mongo = Mongo()
raw_data = mongo.find('t2_job', columns_conditions={'job_area': 1, '_id': 0}, limit=5000)
df = pd.DataFrame(raw_data)
df

         job_area
0       北京·朝阳区·红庙
1     北京·海淀区·北太平庄
2       北京·朝阳区·望京
3              上海
4      北京·东城区·安定门
...           ...
4995   北京·朝阳区·朝阳路
4996    北京·通州区·乔庄
4997   上海·长宁区·新华路
4998   北京·海淀区·苏州街
4999    上海·闵行区·浦江

[5000 rows x 1 columns]

In [40]:
df['city'] = df.job_area.map(lambda x: x.split('·')[0])
df.head(5)

pandas.core.series.Series

In [28]:
city_statistic = df.groupby('city').count()
city_statistic

      job_area
city
上海        2243
北京        2757

In [38]:
df.city.value_counts().to_dict()

{'北京': 2757, '上海': 2243}

## 薪资区间